export const Users = [
  {
    id: 1,
    ProfilePicture: "/assets/person/1.jpeg",
    username: "User1 ",
  },
  {
    id: 2,
    ProfilePicture: "/assets/person/2.jpeg",
    username: "User2 ",
  },
  {
    id: 3,
    ProfilePicture: "/assets/person/3.jpeg",
    username: "User3 ",
  },
  {
    id: 4,
    ProfilePicture: "/assets/person/4.jpeg",
    username: "User4 ",
  },
  {
    id: 5,
    ProfilePicture: "/assets/person/5.jpeg",
    username: "User5 ",
  },
  {
    id: 6,
    ProfilePicture: "/assets/person/6.jpeg",
    username: "User6 ",
  },
  {
    id: 7,
    ProfilePicture: "/assets/person/7.jpeg",
    username: "User7 ",
  },
  {
    id: 8,
    ProfilePicture: "/assets/person/8.jpeg",
    username: "User8 ",
  },
  {
    id: 9,
    ProfilePicture: "/assets/person/9.jpeg",
    username: "User9 ",
  },
  {
    id: 10,
    ProfilePicture: "/assets/person/10.jpeg",
    username: "User10 ",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Description Sample",
    photo: "/assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Description Sample",
    photo: "/assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 30,
    comment: 11,
  },
  {
    id: 3,
    photo: "/assets/post/3.jpeg",
    date: "25 mins ago",
    userId: 3,
    like: 28,
    comment: 13,
  },
  {
    id: 4,
    photo: "/assets/post/4.jpeg",
    date: "35 mins ago",
    userId: 4,
    like: 26,
    comment: 15,
  },
  {
    id: 5,
    desc: "Description Sample",
    photo: "/assets/post/5.jpeg",
    date: "45 mins ago",
    userId: 5,
    like: 24,
    comment: 17,
  },
  {
    id: 6,
    desc: "Description Sample",
    photo: "/assets/post/6.jpeg",
    date: "55 mins ago",
    userId: 6,
    like: 22,
    comment: 19,
  },
  {
    id: 7,
    desc: "Description Sample",
    photo: "/assets/post/7.jpeg",
    date: "65 mins ago",
    userId: 7,
    like: 20,
    comment: 21,
  },
  {
    id: 8,
    desc: "Description Sample",
    photo: "/assets/post/1.jpeg",
    date: "75 mins ago",
    userId: 8,
    like: 18,
    comment: 23,
  },
  {
    id: 9,
    desc: "Description Sample",
    photo: "/assets/post/9.jpeg",
    date: "85 mins ago",
    userId: 9,
    like: 16,
    comment: 25,
  },
  {
    id: 10,
    desc: "Description Sample",
    photo: "/assets/post/10.jpeg",
    date: "95 mins ago",
    userId: 10,
    like: 14,
    comment: 27,
  },
];
